// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Player = __t.object("Player", {
  identity: __t.identity(),
  name: __t.string(),
  lastSubmittedAt: __t.timestamp(),
});
export type Player = __Infer<typeof Player>;

export const Score = __t.object("Score", {
  id: __t.u64(),
  identity: __t.identity(),
  name: __t.string(),
  level: __t.u32(),
  kills: __t.u32(),
  damage: __t.u32(),
  timeSeconds: __t.u32(),
  submittedAt: __t.timestamp(),
});
export type Score = __Infer<typeof Score>;

